name = "NoncommutativeGraphs"
uuid = "3c3e07df-3689-4029-aba7-dd69ca7e6285"
authors = ["Dan Stahlke <dan@stahlke.org>"]
version = "0.1.0"

[deps]
Convex = "f65535da-76fb-5f13-bab9-19810c17039a"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RandomMatrices = "2576dda1-a324-5b11-aa66-c48ed7e3c618"
SCS = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"
Subspaces = "922a6ab9-c04b-46bc-b8bf-400344129a3c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Subspaces = "0.1"
